In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [3]:
df = pd.read_csv(path)
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [4]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0             41   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7             41   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1             41   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0             41   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0             41   

   WindSpeed9am  WindSpeed3pm  Humidity9am  ...  WindDir3pm_NNW  \
0            17            20           92  ...           False   
1             9            13           83  ...           False   
2            17             2           88  ...           False   
3            22            20           83  ...           False   
4            11             6           88  ...           False   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0          False         False          False           False            True   
1          False         False          False           False           False   
2          False         False          False           False           False   
3          False         False          False           False           False   
4          False         False          False           False           False   

   WindDir3pm_SW WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0          False        False           False           False  
1          False        False           False           False  
2          False        False           False           False  
3          False        False           False           False  
4          False         True           False           False  

[5 rows x 68 columns]

In [5]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)
df_sydney_processed.head()

/var/folders/yx/clxpf83j5s5ggm6y06shpr2nvnkgps/T/ipykernel_80177/3565131877.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)


Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0             41   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7             41   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1             41   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0             41   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0             41   

   WindSpeed9am  WindSpeed3pm  Humidity9am  ...  WindDir3pm_NNW  \
0            17            20           92  ...           False   
1             9            13           83  ...           False   
2            17             2           88  ...           False   
3            22            20           83  ...           False   
4            11             6           88  ...           False   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0          False         False          False           False            True   
1          False         False          False           False           False   
2          False         False          False           False           False   
3          False         False          False           False           False   
4          False         False          False           False           False   

   WindDir3pm_SW  WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0          False         False           False           False  
1          False         False           False           False  
2          False         False           False           False  
3          False         False           False           False  
4          False          True           False           False  

[5 rows x 68 columns]

In [6]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [7]:
df_sydney_processed = df_sydney_processed.astype(float)

In [8]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train,  y_test = train_test_split(features, Y, test_size = 0.2, random_state = 10)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(2616, 66)
(2616,)
(655, 66)
(655,)


In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
LinearReg = LinearRegression()
LinearReg

LinearRegression()

In [19]:
LinearReg.fit(X_train, y_train)

LinearRegression()

In [20]:
predictions = LinearReg.predict(X_test)
predictions[0:5]

array([0.13183022, 0.27618694, 0.97819901, 0.28744984, 0.13240051])

In [21]:
import sklearn.metrics as metrics

In [34]:
LinearRegression_MAE = metrics.mean_absolute_error(y_test, predictions)
LinearRegression_MSE = metrics.mean_squared_error(y_test, predictions)
LinearRegression_R2 = metrics.r2_score(y_test, predictions)
print("LinearRegression_MAE: ", LinearRegression_MAE)
print("LinearRegression_MSE: ", LinearRegression_MSE)
print("LinearRegression_R2: ", LinearRegression_R2)

LinearRegression_MAE:  0.18167938931297709
LinearRegression_MSE:  0.18167938931297709
LinearRegression_R2:  0.10060694175205365


In [35]:
Report = {"Metrics":["MAE","MSE","R2"],"Result": 
[LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2]}
pd.DataFrame(Report)

Metrics    Result
0     MAE  0.181679
1     MSE  0.181679
2      R2  0.100607

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
KNN = KNeighborsClassifier(n_neighbors=4)
KNN.fit(X_train, y_train)
KNN

KNeighborsClassifier(n_neighbors=4)

In [38]:
predictions = KNN.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

In [39]:
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [40]:
KNN_Accuracy_Score = accuracy_score(predictions, y_test)
KNN_JaccardIndex = jaccard_score(predictions, y_test)
KNN_F1_Score = f1_score(predictions, y_test)

In [41]:
Report = {"Metrics":["KNN_Accuracy_Score","KNN_JaccardIndex","KNN_F1_Score"],"Result": 
[KNN_Accuracy_Score,KNN_JaccardIndex,KNN_F1_Score]}
pd.DataFrame(Report)

Metrics    Result
0  KNN_Accuracy_Score  0.818321
1    KNN_JaccardIndex  0.425121
2        KNN_F1_Score  0.596610

In [44]:
from sklearn.tree import DecisionTreeClassifier

In [45]:
Tree = DecisionTreeClassifier(criterion='entropy', max_depth=4)
Tree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [48]:
predictions = Tree.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

In [49]:
Tree_Accuracy_Score =  accuracy_score(y_test, predictions)
Tree_JaccardIndex =  jaccard_score(y_test, predictions)
Tree_F1_Score =  f1_score(y_test, predictions)

Report = {"Metrics":["Tree_Accuracy_Score","Tree_JaccardIndex","Tree_F1_Score"],"Result": 
[Tree_Accuracy_Score,Tree_JaccardIndex,Tree_F1_Score]}
pd.DataFrame(Report)

Metrics    Result
0  Tree_Accuracy_Score  0.818321
1    Tree_JaccardIndex  0.480349
2        Tree_F1_Score  0.648968

In [50]:
X_train, X_test, y_train,  y_test = train_test_split(features, Y, test_size = 0.2, random_state = 1)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(2616, 66)
(2616,)
(655, 66)
(655,)


In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
LR = LogisticRegression(solver='liblinear')
LR.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [53]:
predictions = LR.predict(X_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

In [57]:
predict_proba = LR.predict_proba(X_test)
predict_proba[0:5]

array([[0.73911545, 0.26088455],
       [0.97440872, 0.02559128],
       [0.53536447, 0.46463553],
       [0.83441887, 0.16558113],
       [0.96853392, 0.03146608]])

In [58]:
from sklearn.metrics import log_loss
LR_Accuracy_Score =   accuracy_score(y_test, predictions)
LR_JaccardIndex =  jaccard_score(y_test, predictions)
LR_F1_Score =  f1_score(y_test, predictions)
LR_Log_Loss = log_loss(y_test, predict_proba)

In [59]:
Report = {"Metrics":["LR_Accuracy_Score","LR_JaccardIndex","LR_F1_Score", "LR_Log_Loss"],"Result": 
[LR_Accuracy_Score,LR_JaccardIndex,LR_F1_Score, LR_Log_Loss]}
pd.DataFrame(Report)

Metrics    Result
0  LR_Accuracy_Score  0.838168
1    LR_JaccardIndex  0.511521
2        LR_F1_Score  0.676829
3        LR_Log_Loss  0.380029

In [60]:
from sklearn import svm

In [61]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(X_train, y_train)
SVM

SVC()

In [62]:
predictions = SVM.predict(X_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

In [63]:
SVM_Accuracy_Score =  accuracy_score(y_test, predictions)
SVM_JaccardIndex =  jaccard_score(y_test, predictions)
SVM_F1_Score =  f1_score(y_test, predictions)

In [64]:
Report = {"Metrics":["SVM_Accuracy_Score","SVM_JaccardIndex","SVM_F1_Score"],"Result": 
[SVM_Accuracy_Score,SVM_JaccardIndex,SVM_F1_Score]}
pd.DataFrame(Report)

Metrics    Result
0  SVM_Accuracy_Score  0.722137
1    SVM_JaccardIndex  0.000000
2        SVM_F1_Score  0.000000

In [65]:
Report = {"Metrics":["MAE","MSE","R2", "KNN_Accuracy_Score","KNN_JaccardIndex","KNN_F1_Score", "Tree_Accuracy_Score","Tree_JaccardIndex","Tree_F1_Score", "LR_Accuracy_Score","LR_JaccardIndex","LR_F1_Score", "LR_Log_Loss", "SVM_Accuracy_Score","SVM_JaccardIndex","SVM_F1_Score"],"Result": 
[LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2, KNN_Accuracy_Score,KNN_JaccardIndex,KNN_F1_Score, Tree_Accuracy_Score,Tree_JaccardIndex,Tree_F1_Score, LR_Accuracy_Score,LR_JaccardIndex,LR_F1_Score, LR_Log_Loss, SVM_Accuracy_Score,SVM_JaccardIndex,SVM_F1_Score]}
pd.DataFrame(Report)

Metrics    Result
0                   MAE  0.181679
1                   MSE  0.181679
2                    R2  0.100607
3    KNN_Accuracy_Score  0.818321
4      KNN_JaccardIndex  0.425121
5          KNN_F1_Score  0.596610
6   Tree_Accuracy_Score  0.818321
7     Tree_JaccardIndex  0.480349
8         Tree_F1_Score  0.648968
9     LR_Accuracy_Score  0.838168
10      LR_JaccardIndex  0.511521
11          LR_F1_Score  0.676829
12          LR_Log_Loss  0.380029
13   SVM_Accuracy_Score  0.722137
14     SVM_JaccardIndex  0.000000
15         SVM_F1_Score  0.000000